blog/urls.py
from django.urls import include, path

from . import views

app_name = "blog"
urlpatterns = [
    path("", views.index, name="index"),
    path("contact_us/", views.contact_us, name="contact_us"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/register/", views.RegisterFormView.as_view(), name="register"),
    path("accounts/profile/", views.UserProfile.as_view(), name="profile"),
    path("accounts/update_profile/", views.UpdateProfile.as_view(), name="update_profile"),
    path("post_create/", views.PostCreateView.as_view(), name="post_create"),
    path("post/<int:pk>", views.PostDetailView.as_view(), name="post_detail"),
    path("post/<int:pk>/update/", views.PostUpdateView.as_view(), name="post_update"),
    path("post/<int:pk>/delete/", views.PostDeleteView.as_view(), name="post_delete"),
    path("post_list/", views.PostListView.as_view(), name="post_list"),
    path("my_post_list/", views.MyPostListView.as_view(), name="my_post_list"),
    path("author_list/", views.AuthorListView.as_view(), name="author_list"),
    path("author/<int:pk>", views.AuthorDetailView.as_view(), name="author_detail"),
    path("post/<int:pk>/comment_create/", views.comment_create, name="comment_create"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
]

if settings.DEBUG:
    urlpatterns += (
        [
            path("__debug__/", include("debug_toolbar.urls")),
        ]
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

templates/includes/author_list.html
{% for a in author %}
    <tr>
        <td>{{ a.id }}</td>
        <td><a href="{% url 'blog:author_detail' a.id %}">{{ a.username }}</a></td>
        <td>{{ a.email }}</td>
        <td>{{ a.about }}</td>
        {% empty %}
    <tr>
        <td colspan="8" class="text-center bg-warning">No Authors</td>
    </tr>
{% endfor %}

templates/includes/contact_us.html
<form method="post" action="{% url 'blog:contact_us' %}" class="js-book-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Contact Us</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    {% include 'includes/contact_us_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Contact Us</button>
  </div>
</form>

templates/includes/contact_us_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class+="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class+="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class+="form-control" %}
    {% endif %}
  </div>
{% endfor %}

templates/includes/return_index.html
<br>
        <form action="" method="get">
            <a href={% url "blog:index" %}>Return to Index</a>
        </form>