blog/urls.py
from django.urls import include, path

from . import views

app_name = "blog"
urlpatterns = [
    path("", views.index, name="index"),
    path("contact_us/", views.contact_us, name="contact_us"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/register/", views.RegisterFormView.as_view(), name="register"),
    path("accounts/profile/", views.UserProfile.as_view(), name="profile"),
    path("accounts/update_profile/", views.UpdateProfile.as_view(), name="update_profile"),
    path("post_create/", views.PostCreateView.as_view(), name="post_create"),
    path("post/<int:pk>", views.PostDetailView.as_view(), name="post_detail"),
    path("post/<int:pk>/update/", views.PostUpdateView.as_view(), name="post_update"),
    path("post/<int:pk>/delete/", views.PostDeleteView.as_view(), name="post_delete"),
    path("post_list/", views.PostListView.as_view(), name="post_list"),
    path("my_post_list/", views.MyPostListView.as_view(), name="my_post_list"),
    path("author_list/", views.AuthorListView.as_view(), name="author_list"),
    path("author/<int:pk>", views.AuthorDetailView.as_view(), name="author_detail"),
    path("post/<int:pk>/comment_create/", views.comment_create, name="comment_create"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
]

if settings.DEBUG:
    urlpatterns += (
        [
            path("__debug__/", include("debug_toolbar.urls")),
        ]
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

blog/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class CustomUser(AbstractUser):  # noqa DJ10, DJ11
    email = models.EmailField(unique=True)
    about = models.CharField(max_length=200)
    avatar = models.ImageField("avatar", upload_to="images", blank=True, null=True)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return f"{self.username}, {self.email}, {self.about}"

    def get_absolute_url(self):
        return reverse("blog:author_detail", kwargs={"pk": self.pk})


class Post(models.Model):  # noqa DJ10, DJ11
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    body = models.TextField()
    image = models.ImageField(upload_to="images", blank=True, null=True)
    is_published = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title}. by {self.author}. Created on: {self.created_on:'%d.%m.%Y, %H:%m'}. "

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"pk": self.pk})


class Comment(models.Model):  # noqa DJ10, DJ11
    post = models.ForeignKey(Post, on_delete=models.SET_NULL, blank=True, null=True)
    author = models.CharField(max_length=50)
    comment_text = models.TextField()
    is_published = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment: {self.comment_text}. Author: {self.author}. {self.created_on:'%d.%m.%Y, %H:%m'}"

blog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from blog.models import Comment

User = get_user_model()


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

    def clean_from_email(self):
        data = self.cleaned_data["from_email"]

        if data.strip().endswith("mail.ru"):
            raise ValidationError(_("We can't send email on mail.ru emails"))

        return data

    def clean(self):
        email = self.cleaned_data["from_email"]
        subject = self.cleaned_data["subject"]

        if email.endswith("gmail.com") and "spam" in subject.lower():
            self.add_error(None, "Can't send spam emails")


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["author", "comment_text"]

blog/views.py
from django.conf import settings
from django.contrib.auth import get_user_model, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count, Q
from django.shortcuts import get_object_or_404, redirect, render
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, FormView, ListView, UpdateView
from django.views.generic.list import MultipleObjectMixin

from . import tasks
from blog.forms import CommentModelForm, ContactForm, RegisterForm
from blog.models import Comment, CustomUser, Post

User = get_user_model()


def index(request):
    """Start page where User can sign up/sign in"""

    posts = (
        Post.objects.filter(is_published=True).annotate(comment_count=Count("comment__id")).order_by("-comment_count")
    )
    return render(request, "blog/index.html", {"posts": posts})


class RegisterFormView(FormView):
    """View for User registration"""

    template_name = "registration/register.html"
    form_class = RegisterForm
    success_url = reverse_lazy("blog:profile")

    def form_valid(self, form):
        user = form.save()
        # user = authenticate(self.request, username=user.username, password=form.cleaned_data.get("password1"))
        login(self.request, user)
        return super(RegisterFormView, self).form_valid(form)


class UserProfile(LoginRequiredMixin, DetailView):
    """View with logged user's information"""

    model = CustomUser
    template_name = "registration/profile.html"

    def get_object(self, queryset=None):
        user = self.request.user
        return user


class UpdateProfile(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """View for updating user's information"""

    model = CustomUser
    fields = ["first_name", "last_name", "email", "about", "avatar"]
    template_name = "registration/update_profile.html"
    success_url = reverse_lazy("blog:profile")
    success_message = "Profile updated"

    def get_object(self, queryset=None):
        user = self.request.user
        return user


class PostCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """View for crating post by logged user"""

    model = Post
    fields = ["title", "description", "body", "image"]
    template_name = "blog/post_create.html"
    success_message = "Post created. Wait for approve by admin"

    def form_valid(self, form):
        post_object = form.save(commit=False)
        post_object.author = self.request.user
        post_object.save()
        post_path = f"http://127.0.0.1:5000/post/{post_object.id}"
        send_mail(
            "New post!",
            loader.render_to_string(
                "blog/new_post_email.html",
                {"author": post_object.author, "title": post_object.title, "post_path": post_path},
            ),
            settings.NOREPLY_EMAIL,
            ["admin@a.com"],
            fail_silently=False,
        )
        return super().form_valid(form)


class PostDetailView(DetailView, MultipleObjectMixin):
    """View with post details"""

    model = Post
    template_name = "blog/post_detail.html"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        comments_list = Comment.objects.filter(post__id=self.object.id, is_published=True)
        context = super(PostDetailView, self).get_context_data(object_list=comments_list, **kwargs)
        paginator = Paginator(comments_list, 10)
        page = self.request.GET.get("page")
        context["image"] = self.object.image
        try:
            comments = paginator.page(page)
        except PageNotAnInteger:
            comments = paginator.page(1)
        except EmptyPage:
            comments = paginator.page(paginator.num_pages)
        context["comments"] = comments
        return context


class PostUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """View for updating post by user-owner"""

    model = Post
    fields = ["title", "description", "body", "image"]
    template_name = "blog/post_update.html"
    success_message = "Post updated"


class PostDeleteView(LoginRequiredMixin, DeleteView):
    """View for post deleting"""

    model = Post
    success_url = reverse_lazy("blog:my_post_list")
    success_message = "Post deleted"

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user)


class PostListView(ListView):
    """Show published Posts with count of Comments for each"""

    model = Post
    context_object_name = "post"
    paginate_by = 10

    def get_queryset(self):
        return (
            Post.objects.filter(is_published=True)
            .annotate(comment_count=Count("comment__id", filter=Q(is_published=True)))
            .order_by("created_on")
        )


class MyPostListView(LoginRequiredMixin, ListView):
    """View show published and draft posts for logged user"""

    model = Post
    context_object_name = "post"
    template_name = "blog/my_post_list.html"
    paginate_by = 10

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user).annotate(comment_count=Count("comment__id"))


class AuthorListView(ListView):
    """View with all registered Authors"""

    model = CustomUser
    context_object_name = "author"
    template_name = "blog/author_list.html"
    paginate_by = 20

    def get_queryset(self):
        return CustomUser.objects.all()


class AuthorDetailView(DetailView):
    """View with author's detail for any users"""

    model = CustomUser
    context_object_name = "author"
    template_name = "blog/author_detail.html"


def comment_create(request, pk):
    """View for creating comment on Post details"""

    post = get_object_or_404(Post, pk=pk)
    user = request.user
    post_path = f"http://127.0.0.1:5000/post/{post.id}"
    if request.method == "POST":
        form = CommentModelForm(request.POST)
        if form.is_valid():
            comment = Comment.objects.create(
                post_id=pk,
                author=form.cleaned_data["author"],
                comment_text=form.cleaned_data["comment_text"],
            )
            send_mail(
                "New post!",
                loader.render_to_string(
                    "blog/new_comment_email.html",
                    {"author": comment.author, "comment": comment.comment_text, "post_path": post_path},
                ),
                settings.NOREPLY_EMAIL,
                ["admin@a.com", f"{post.author.email}"],
                fail_silently=False,
            )
            return redirect(reverse("blog:post_detail", args=(pk,)))
    else:
        if user.is_authenticated:
            form = CommentModelForm(initial={"author": request.user.username})
        else:
            form = CommentModelForm()
    return render(request, "blog/create_comment.html", {"form": form, "post": post})


def contact_us(request):
    """Contact form"""

    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            tasks.post_email(
                form.cleaned_data.get("subject"),
                form.cleaned_data.get("message"),
                [form.cleaned_data.get("from_email")],
            )
            return redirect(reverse("blog:index"))
    else:
        form = ContactForm()
    return render(request, "blog/partial_contact_create.html", {"form": form})

templates/blog/author_detail.html
{% extends 'blog/base.html' %}
{% block title %} {% endblock title %}
{% load static %}
{% block css_additional %}
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
{% endblock css_additional %}
{% block content %}
    <form action="{% url 'blog:author_detail' author.id %}" method="GET" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset>
            <div class="card" style="width:300px">
                <h3 class="card-title" align="center">Author Information: </h3>
                {% if object.avatar %}
                    <img class="img-fluid" src="{{ object.avatar.url }}" alt="Card image">
                {% endif %}
                <div class="card-body">
                    <h4 class="card-title">{{ object.username }}</h4>
                    <p class="card-text"><b>Email:</b> {{ object.email }}</p>
                    <p class="card-text"><b>First name:</b> {{ object.first_name }}</p>
                    <p class="card-text"><b>Last name:</b> {{ object.last_name }}</p>
                    <p class="card-text"><b>About:</b> {{ object.about }}</p>
                </div>
            </div>
        </fieldset>
    </form>
    {% include 'includes/return_index.html' %}
{% endblock content %}

templates/blog/author_list.html
{% extends 'blog/base.html' %}


{% block title %} Index {% endblock title %}
{% load static %}
{% block css_additional %}
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
{% endblock css_additional %}
{% block content %}
    <form action="{% url 'blog:author_list' %}" method="GET">
        {% csrf_token %}
        <fieldset>
            <h1 class="page-header">Authors</h1>

            <table class="table" id="book-table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>User</th>
                    <th>Email</th>
                    <th>About</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% include 'includes/author_list.html' %}
                </tbody>
            </table>

            <div class="modal fade" id="modal-book">
                <div class="modal-dialog">
                    <div class="modal-content">

                    </div>
                </div>
            </div>
        </fieldset>
    </form>
    {% include 'includes/return_index.html' %}
{% endblock content %}

templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock title %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
    {% block css_additional %}
        <script src="{% static 'js/contact_us.js' %}"></script>
        <link rel="stylesheet" href="{% static 'blog/project_style.css' %}">
    {% endblock %}
    {% block extra_css %}
    {% endblock %}
    {% block extra_js %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-info">
    <a class="navbar-brand" style="padding-left: 30px;" href="{% url 'blog:index' %}">Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="main-menu">
        <ul class="navbar-nav mr-auto">
            <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal"><a class="nav-link"
                                                                                                     href="{% url 'blog:contact_us' %}">Contact
                Us...</a></button>
            {% if user.is_authenticated %}
                <button type="button" class="btn btn-info"><a class="nav-link" href="{% url 'blog:logout' %}">Logout</a>
                </button>
            {% endif %}
        </ul>
    </div>
</nav>
<br>
<br>


<div class="container" style="padding-top: 30px;">
    <div class="container-fluid">

        {% if messages %}
            <div class="row">
                <div class="col-sm-12">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error{% else %}
                                {{ message.tags|title }}{% endif %}!</strong> {{ message }}
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                    <ul class="sidebar-nav">
                        <li><a href="{% url 'blog:index' %}">Home</a></li>
                        <li><a href="{% url 'blog:post_list' %}">All Posts</a></li>
                        <li><a href="{% url 'blog:author_list' %}">All Authors</a></li>
                    </ul>

                    <ul class="sidebar-nav">
                        {% if user.is_authenticated %}
                            <li>User: <b>{{ user.get_username }}</b></li>
                            <li><a href="{% url 'blog:profile' %}">My profile</a></li>
                            <li><a href="{% url 'blog:my_post_list' %}">My Posts</a></li>
                            <li><a href="{% url 'blog:post_create' %}">Create Post</a></li>
                        {% else %}
                            <li><a href="{% url 'blog:login' %}">Login</a></li>
                            <li><a href="{% url 'blog:register' %}">Register</a></li>
                        {% endif %}
                    </ul>
                    {% if user.is_staff %}
                        <hr/>
                        <ul class="sidebar-nav">
                            <li>Staff</li>
                        </ul>
                    {% endif %}

                {% endblock %}
            </div>
            <div class="col-sm-10 ">
                {% block content %} {% endblock content %}
                {% block pagination %}
                    {% if is_paginated %}
                        <div class="pagination">
                        <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                            <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                            {% if page_obj.has_next %}
                                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                            {% endif %}
                </span>

                    {% endif %}
                {% endblock %}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modal-contact">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>
</body>
</html>

templates/blog/create_comment.html
{% extends 'blog/base.html' %}


{% block title %} Index {% endblock title %}
{% load static %}
{% block css_additional %}
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
{% endblock css_additional %}
{% block content %}
    <form action="{% url 'blog:comment_create' post.id %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <legend><h3>Create Comment: </h3></legend>
            {% if user.is_authenticate %}

            {% endif %}
            {{ form.as_p }}
            <input type="submit" value="Create!">
        </fieldset>
    </form>
    <a href="{% url 'blog:post_list' %}">Return to Post list</a>
    {% include 'includes/return_index.html' %}
{% endblock content %}

templates/blog/index.html
{% extends 'blog/base.html' %}


{% block title %} Index {% endblock title %}
{% load static %}
{% block css_additional %}
        <link rel="stylesheet" href="{% static 'blog/style.css' %}">
{% endblock css_additional %}
{% block content %}
    <form action="{% url 'blog:index' %}" method="GET">
        {% csrf_token %}
        <fieldset>
            <legend><h2>Popular posts: </h2></legend>
        <ul class="list-group list-group-flush">
            {% for post in posts %}
                <li class="list-group-item"><a href="{% url 'blog:post_detail' post.id %}?next={{ request.path }}">{{ post }} </a>
                    <span class="badge bg-warning">  Comments: {{ post.comment_count }}</span></li>
{#                Comments: {{ post.comment_count }}</li>#}
            {% endfor %}
        </ul>
        </fieldset>
        <br>
    </form>
{% endblock content %}

templates/blog/my_post_list.html
{% extends 'blog/base.html' %}


{% block title %} Index {% endblock title %}
{% load static %}
{% block css_additional %}
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
{% endblock css_additional %}
{% block content %}
    <form action="{% url 'blog:my_post_list' %}" method="GET">
        {% csrf_token %}
        <fieldset>
            <legend><h2>My posts: </h2></legend>
            <h3>Published posts:</h3>
            <ul class="list-group list-group-flush">
                {% for p in post %}
                    {% if p.is_published %}
                        <li class="list-group-item"><a href="{% url 'blog:post_detail' p.id %}">{{ p }}</a>
                            <span class="badge bg-success">  Comments: {{ p.comment_count }}</span></li>
                    {% endif %}
                {% endfor %}
                <br>
                <br>
                <h3>Draft posts (waiting for moderation):</h3>
                {% for p in post %}
                    {% if p.is_published == 0 %}
                        <li class="list-group-item"><a href="{% url 'blog:post_detail' p.id %}">{{ p }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </fieldset>
    </form>
    <button class="btn btn-outline-success"><a href="{% url 'blog:post_create' %}">Create Post</a></button>
    {% include 'includes/return_index.html' %}
{% endblock content %}

templates/blog/new_comment_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tilin-tilin</title>
</head>
<body>
<h3>Hello! New comment waiting for approve</h3>
<p>Author: {{ author }}</p>
<p>Comment: '{{ comment }}'</p>
<p>Post: {{ post_path }}</p>
</body>
</html>

templates/blog/new_post_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tilin-tilin</title>
</head>
<body>
<h3>Hello! New post waiting for your approve</h3>
<p>{{ author }}</p>
<p>Post: '{{ title }}'</p>
<p>Post path: '{{ post_path }}'</p>
</body>
</html>

templates/blog/partial_contact_create.html
{% extends 'blog/base.html' %}

{% block content %}
    <form action="{% url 'blog:contact_us' %}" method="POST" class="js-contact-form">
        {% csrf_token %}
        <h2 align="center">You can write us</h2>
        <div class="text-center">
            <button type="button" class="btn btn-danger " data-toggle="modal" data-target="#myModal">
                Open contact form
            </button>
        </div>

        <!-- The Modal -->
        <div class="container">

            <div class="modal" id="myModal">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h4 class="modal-title">Modal Heading</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>

                        <!-- Modal body -->
                        <div class="modal-body">
                            {% include 'blog/partial_contact_form.html' %}
                        </div>

                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success" >Go!</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </form>
{% endblock content %}

templates/blog/partial_contact_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label>{{ field.label }}</label>
    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class+="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class+="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class+="form-control" %}
    {% endif %}
  </div>
{% endfor %}

templates/blog/post_create.html
{% extends 'blog/base.html' %}
{% load widget_tweaks %}

{% block title %} Index {% endblock title %}
{% load static %}
{% block css_additional %}
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
{% endblock css_additional %}
{% block content %}
    <form action="{% url 'blog:post_create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
                <label>{{ field.label }}</label>
                {% if form.is_bound %}
                    {% if field.errors %}
                        {% render_field field class+="form-control is-invalid" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field field class+="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field field class+="form-control" %}
                {% endif %}
            </div>
        {% endfor %}
        <br>
        <input class="btn btn-success" type="submit" value="Create!">
    </form>
    <a href="{% url 'blog:post_list' %}">Return to Post list</a>
    {% include 'includes/return_index.html' %}
{% endblock content %}

templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block title %} {% endblock title %}
{% load static %}
{% block css_additional %}
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
{% endblock css_additional %}
{% block content %}
    <form action="{% url 'blog:post_detail' post.id %}" method="GET" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset>
            <legend><h2>Post Information: </h2></legend>
            <h3>{{ post }}</h3>
            {% if post.image %}
                <img src="{{ post.image.url }}" alt="">
            {% endif %}
            {% for comment in comments %}
                {% if comment.is_published %}
                    <li>{{ comment }}</li>
                {% endif %}
            {% endfor %}
            <br>
            <br>
            {% if post.is_published %}
                <button class="btn btn-outline-success"><a href="{% url 'blog:comment_create' post.id %}">Create
                    comment</a></button>
            {% else %}
                <b>Your post waiting for approve. You cant comment draft post</b>
                <br>
                <br>
            {% endif %}
            <br>
            <br>
            {% if post.author == request.user or request.user.is_superuser %}
                <div>
                    <button class="btn btn-success"><a href="{% url 'blog:post_update' post.id %}">Update Post</a>
                    </button>
                    <button class="btn btn-danger"><a href="{% url 'blog:post_delete' post.id %}">Delete Post</a>
                    </button>
                </div>
            {% endif %}

        </fieldset>
    </form>
    <a href="{% url 'blog:post_list' %}">Return to Post list</a>
    {% include 'includes/return_index.html' %}

{% endblock content %}

templates/blog/post_list.html
{% extends 'blog/base.html' %}


{% block title %} Index {% endblock title %}
{% load static %}
{% block css_additional %}
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
{% endblock css_additional %}
{% block content %}
    <form action="{% url 'blog:post_list' %}" method="GET">
        {% csrf_token %}
        <fieldset>
            <legend><h2>All posts: </h2></legend>
            <ul class="list-group list-group-flush">

                {% for p in post %}
                    <li class="list-group-item"><a href="{% url 'blog:post_detail' p.id %}">{{ p }}</a>
                        <span class="badge bg-warning">  Comments: {{ p.comment_count }}</span></li>
                {% endfor %}

            </ul>
        </fieldset>
    </form>
    <button class="btn btn-outline-success"><a href="{% url 'blog:post_create' %}">Create Post</a></button>
    {% include 'includes/return_index.html' %}
{% endblock content %}

templates/blog/post_update.html
{% extends 'blog/base.html' %}


{% block title %} Index {% endblock title %}
{% load static %}
{% block css_additional %}
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
{% endblock css_additional %}
{% block content %}
    <form action="{% url 'blog:post_update' post.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset>
            <legend><h3>Update Post: </h3></legend>
            {{ form.as_p }}
            <input type="submit" value="Update Post">
        </fieldset>
    </form>
    <a href="{% url 'blog:post_list' %}">Return to Post list</a>
    {% include 'includes/return_index.html' %}
{% endblock content %}